-- Migration: Add ElevenLabs conversation data fields to call_logs table
-- Date: 2024-01-15
-- Description: Adds fields to store call summary and end reason from ElevenLabs post-call webhooks

-- Add call_summary column to store AI-generated conversation summary
ALTER TABLE call_logs 
ADD COLUMN call_summary TEXT DEFAULT NULL 
COMMENT 'Summary of the call generated by AI';

-- Add call_end_reason column to store how the call ended
ALTER TABLE call_logs 
ADD COLUMN call_end_reason VARCHAR(100) DEFAULT NULL 
COMMENT 'Reason why the call ended (e.g., user_hangup, agent_hangup, error, timeout)';

-- The following fields are already covered by existing columns:
-- - transcription (TEXT) - stores the full transcript
-- - duration (INTEGER) - stores call duration in seconds
-- - metadata (JSON) - stores additional ElevenLabs data like conversation_id, agent_id, etc.
-- - status (ENUM) - stores call status (completed, failed, etc.)
-- - ended_at (DATE) - stores when the call ended
