/**
 * Call Log Model
 * Defines the CallLog schema for storing call metadata
 */
const { DataTypes } = require('sequelize');
const { sequelize } = require('../../config/db');

/**
 * Valid call directions
 */
const CALL_DIRECTION = {
  INBOUND: 'inbound',
  OUTBOUND: 'outbound',
};

/**
 * Valid call statuses
 */
const CALL_STATUS = {
  INITIATED: 'initiated',
  RINGING: 'ringing',
  IN_PROGRESS: 'in-progress',
  COMPLETED: 'completed',
  BUSY: 'busy',
  NO_ANSWER: 'no-answer',
  CANCELED: 'canceled',
  FAILED: 'failed',
};

const CallLog = sequelize.define('CallLog', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true,
  },
  tenantId: {
    type: DataTypes.UUID,
    allowNull: false,
    field: 'tenant_id',
    references: {
      model: 'tenants',
      key: 'id',
    },
  },
  twilioCallSid: {
    type: DataTypes.STRING(64),
    allowNull: false,
    unique: true,
    field: 'twilio_call_sid',
  },
  direction: {
    type: DataTypes.ENUM(...Object.values(CALL_DIRECTION)),
    allowNull: false,
  },
  status: {
    type: DataTypes.ENUM(...Object.values(CALL_STATUS)),
    defaultValue: CALL_STATUS.INITIATED,
    allowNull: false,
  },
  fromNumber: {
    type: DataTypes.STRING(20),
    allowNull: false,
    field: 'from_number',
  },
  toNumber: {
    type: DataTypes.STRING(20),
    allowNull: false,
    field: 'to_number',
  },
  duration: {
    type: DataTypes.INTEGER,
    allowNull: true,
    comment: 'Call duration in seconds',
  },
  startedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'started_at',
  },
  endedAt: {
    type: DataTypes.DATE,
    allowNull: true,
    field: 'ended_at',
  },
  recordingUrl: {
    type: DataTypes.STRING(500),
    allowNull: true,
    field: 'recording_url',
  },
  transcription: {
    type: DataTypes.TEXT,
    allowNull: true,
  },
  callSummary: {
    type: DataTypes.TEXT,
    allowNull: true,
    field: 'call_summary',
    comment: 'Summary of the call generated by AI',
  },
  callEndReason: {
    type: DataTypes.STRING(100),
    allowNull: true,
    field: 'call_end_reason',
    comment: 'Reason why the call ended (e.g., user_hangup, agent_hangup, etc.)',
  },
  metadata: {
    type: DataTypes.JSON,
    allowNull: true,
    defaultValue: {},
  },
}, {
  tableName: 'call_logs',
  timestamps: true,
  indexes: [
    {
      fields: ['tenant_id'],
    },
    {
      fields: ['twilio_call_sid'],
    },
    {
      fields: ['created_at'],
    },
  ],
});

/**
 * Get call log data safe for API response
 * @returns {Object} - Call log data
 */
CallLog.prototype.toSafeObject = function() {
  return this.toJSON();
};

/**
 * Update call log from Twilio webhook data
 * @param {Object} twilioData - Data from Twilio webhook
 * @returns {Promise<CallLog>} - Updated call log
 */
CallLog.prototype.updateFromTwilio = async function(twilioData) {
  if (twilioData.CallStatus) {
    this.status = twilioData.CallStatus;
  }
  if (twilioData.CallDuration) {
    this.duration = parseInt(twilioData.CallDuration, 10);
  }
  if (twilioData.RecordingUrl) {
    this.recordingUrl = twilioData.RecordingUrl;
  }
  await this.save();
  return this;
};

/**
 * Update call log from ElevenLabs webhook data
 * @param {Object} elevenLabsData - Data from ElevenLabs conversation end webhook
 * @returns {Promise<CallLog>} - Updated call log
 */
CallLog.prototype.updateFromElevenLabs = async function(elevenLabsData) {
  // Update status based on call outcome
  if (elevenLabsData.status === 'done' || elevenLabsData.call_successful) {
    this.status = CALL_STATUS.COMPLETED;
  } else if (elevenLabsData.status === 'failed') {
    this.status = CALL_STATUS.FAILED;
  }
  
  // Update duration from ElevenLabs data (in seconds)
  if (elevenLabsData.call_duration_secs !== undefined) {
    this.duration = Math.floor(elevenLabsData.call_duration_secs);
  }
  
  // Update end reason
  if (elevenLabsData.end_reason) {
    this.callEndReason = elevenLabsData.end_reason;
  }
  
  // Update call summary
  if (elevenLabsData.transcript_summary) {
    this.callSummary = elevenLabsData.transcript_summary;
  }
  
  // Update transcript if available
  if (elevenLabsData.transcript) {
    // If transcript is an array of messages, format it
    if (Array.isArray(elevenLabsData.transcript)) {
      this.transcription = elevenLabsData.transcript
        .map(msg => `${msg.role || 'unknown'}: ${msg.message || msg.content || ''}`)
        .join('\n');
    } else if (typeof elevenLabsData.transcript === 'string') {
      this.transcription = elevenLabsData.transcript;
    }
  }
  
  // Store conversation end time
  if (elevenLabsData.end_timestamp || elevenLabsData.ended_at) {
    this.endedAt = new Date(elevenLabsData.end_timestamp || elevenLabsData.ended_at);
  }
  
  // Store ElevenLabs conversation ID and additional metadata
  if (!this.metadata) {
    this.metadata = {};
  }
  
  if (elevenLabsData.conversation_id) {
    this.metadata.elevenLabsConversationId = elevenLabsData.conversation_id;
  }
  
  if (elevenLabsData.agent_id) {
    this.metadata.elevenLabsAgentId = elevenLabsData.agent_id;
  }
  
  // Store any additional relevant metadata
  this.metadata.elevenLabsCallSuccessful = elevenLabsData.call_successful;
  
  if (elevenLabsData.user_satisfaction_rating !== undefined) {
    this.metadata.elevenLabsUserSatisfactionRating = elevenLabsData.user_satisfaction_rating;
  }
  
  await this.save();
  return this;
};

module.exports = {
  CallLog,
  CALL_DIRECTION,
  CALL_STATUS,
};
